
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model TwitchFollow
 * 
 */
export type TwitchFollow = Prisma.TwitchFollowModel
/**
 * Model TwitchSubscription
 * 
 */
export type TwitchSubscription = Prisma.TwitchSubscriptionModel
/**
 * Model TwitchCheer
 * 
 */
export type TwitchCheer = Prisma.TwitchCheerModel
/**
 * Model TwitchStream
 * 
 */
export type TwitchStream = Prisma.TwitchStreamModel
/**
 * Model TwitchRaid
 * 
 */
export type TwitchRaid = Prisma.TwitchRaidModel
/**
 * Model TwitchRedemption
 * 
 */
export type TwitchRedemption = Prisma.TwitchRedemptionModel
/**
 * Model TwitchChannelUpdate
 * 
 */
export type TwitchChannelUpdate = Prisma.TwitchChannelUpdateModel
/**
 * Model TwitchResub
 * 
 */
export type TwitchResub = Prisma.TwitchResubModel
/**
 * Model TwitchGiftSub
 * 
 */
export type TwitchGiftSub = Prisma.TwitchGiftSubModel
