
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Account: 'Account',
  Session: 'Session',
  TwitchFollow: 'TwitchFollow',
  TwitchSubscription: 'TwitchSubscription',
  TwitchCheer: 'TwitchCheer',
  TwitchStream: 'TwitchStream',
  TwitchRaid: 'TwitchRaid',
  TwitchRedemption: 'TwitchRedemption',
  TwitchChannelUpdate: 'TwitchChannelUpdate'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  isValid: 'isValid',
  createdAt: 'createdAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state',
  createdAt: 'createdAt'
} as const

export type AccountScalarFieldEnum = (typeof AccountScalarFieldEnum)[keyof typeof AccountScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires',
  createdAt: 'createdAt'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const TwitchFollowScalarFieldEnum = {
  id: 'id',
  channelId: 'channelId',
  followerId: 'followerId',
  followerName: 'followerName',
  followedAt: 'followedAt',
  createdAt: 'createdAt'
} as const

export type TwitchFollowScalarFieldEnum = (typeof TwitchFollowScalarFieldEnum)[keyof typeof TwitchFollowScalarFieldEnum]


export const TwitchSubscriptionScalarFieldEnum = {
  id: 'id',
  channelId: 'channelId',
  subscriberId: 'subscriberId',
  subscriberName: 'subscriberName',
  isGift: 'isGift',
  gifterId: 'gifterId',
  gifterName: 'gifterName',
  isAnonymous: 'isAnonymous',
  tier: 'tier',
  createdAt: 'createdAt'
} as const

export type TwitchSubscriptionScalarFieldEnum = (typeof TwitchSubscriptionScalarFieldEnum)[keyof typeof TwitchSubscriptionScalarFieldEnum]


export const TwitchCheerScalarFieldEnum = {
  id: 'id',
  channelId: 'channelId',
  cheererId: 'cheererId',
  cheererName: 'cheererName',
  bits: 'bits',
  message: 'message',
  createdAt: 'createdAt'
} as const

export type TwitchCheerScalarFieldEnum = (typeof TwitchCheerScalarFieldEnum)[keyof typeof TwitchCheerScalarFieldEnum]


export const TwitchStreamScalarFieldEnum = {
  id: 'id',
  channelId: 'channelId',
  type: 'type',
  streamType: 'streamType',
  startedAt: 'startedAt',
  createdAt: 'createdAt'
} as const

export type TwitchStreamScalarFieldEnum = (typeof TwitchStreamScalarFieldEnum)[keyof typeof TwitchStreamScalarFieldEnum]


export const TwitchRaidScalarFieldEnum = {
  id: 'id',
  channelId: 'channelId',
  raiderId: 'raiderId',
  raiderName: 'raiderName',
  viewers: 'viewers',
  createdAt: 'createdAt'
} as const

export type TwitchRaidScalarFieldEnum = (typeof TwitchRaidScalarFieldEnum)[keyof typeof TwitchRaidScalarFieldEnum]


export const TwitchRedemptionScalarFieldEnum = {
  id: 'id',
  channelId: 'channelId',
  redeemerId: 'redeemerId',
  redeemerName: 'redeemerName',
  rewardId: 'rewardId',
  rewardTitle: 'rewardTitle',
  rewardCost: 'rewardCost',
  userInput: 'userInput',
  redeemedAt: 'redeemedAt',
  createdAt: 'createdAt'
} as const

export type TwitchRedemptionScalarFieldEnum = (typeof TwitchRedemptionScalarFieldEnum)[keyof typeof TwitchRedemptionScalarFieldEnum]


export const TwitchChannelUpdateScalarFieldEnum = {
  id: 'id',
  channelId: 'channelId',
  title: 'title',
  categoryId: 'categoryId',
  categoryName: 'categoryName',
  language: 'language',
  createdAt: 'createdAt'
} as const

export type TwitchChannelUpdateScalarFieldEnum = (typeof TwitchChannelUpdateScalarFieldEnum)[keyof typeof TwitchChannelUpdateScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

