
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TwitchUser` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TwitchUser
 * 
 */
export type TwitchUserModel = runtime.Types.Result.DefaultSelection<Prisma.$TwitchUserPayload>

export type AggregateTwitchUser = {
  _count: TwitchUserCountAggregateOutputType | null
  _min: TwitchUserMinAggregateOutputType | null
  _max: TwitchUserMaxAggregateOutputType | null
}

export type TwitchUserMinAggregateOutputType = {
  id: string | null
  accessToken: string | null
  refreshToken: string | null
  expiresAt: Date | null
  scope: string | null
  isValid: boolean | null
  login: string | null
  displayName: string | null
  profileImage: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TwitchUserMaxAggregateOutputType = {
  id: string | null
  accessToken: string | null
  refreshToken: string | null
  expiresAt: Date | null
  scope: string | null
  isValid: boolean | null
  login: string | null
  displayName: string | null
  profileImage: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TwitchUserCountAggregateOutputType = {
  id: number
  accessToken: number
  refreshToken: number
  expiresAt: number
  scope: number
  isValid: number
  login: number
  displayName: number
  profileImage: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TwitchUserMinAggregateInputType = {
  id?: true
  accessToken?: true
  refreshToken?: true
  expiresAt?: true
  scope?: true
  isValid?: true
  login?: true
  displayName?: true
  profileImage?: true
  createdAt?: true
  updatedAt?: true
}

export type TwitchUserMaxAggregateInputType = {
  id?: true
  accessToken?: true
  refreshToken?: true
  expiresAt?: true
  scope?: true
  isValid?: true
  login?: true
  displayName?: true
  profileImage?: true
  createdAt?: true
  updatedAt?: true
}

export type TwitchUserCountAggregateInputType = {
  id?: true
  accessToken?: true
  refreshToken?: true
  expiresAt?: true
  scope?: true
  isValid?: true
  login?: true
  displayName?: true
  profileImage?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TwitchUserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TwitchUser to aggregate.
   */
  where?: Prisma.TwitchUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TwitchUsers to fetch.
   */
  orderBy?: Prisma.TwitchUserOrderByWithRelationInput | Prisma.TwitchUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TwitchUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TwitchUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TwitchUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TwitchUsers
  **/
  _count?: true | TwitchUserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TwitchUserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TwitchUserMaxAggregateInputType
}

export type GetTwitchUserAggregateType<T extends TwitchUserAggregateArgs> = {
      [P in keyof T & keyof AggregateTwitchUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTwitchUser[P]>
    : Prisma.GetScalarType<T[P], AggregateTwitchUser[P]>
}




export type TwitchUserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TwitchUserWhereInput
  orderBy?: Prisma.TwitchUserOrderByWithAggregationInput | Prisma.TwitchUserOrderByWithAggregationInput[]
  by: Prisma.TwitchUserScalarFieldEnum[] | Prisma.TwitchUserScalarFieldEnum
  having?: Prisma.TwitchUserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TwitchUserCountAggregateInputType | true
  _min?: TwitchUserMinAggregateInputType
  _max?: TwitchUserMaxAggregateInputType
}

export type TwitchUserGroupByOutputType = {
  id: string
  accessToken: string
  refreshToken: string
  expiresAt: Date
  scope: string
  isValid: boolean
  login: string
  displayName: string
  profileImage: string | null
  createdAt: Date
  updatedAt: Date
  _count: TwitchUserCountAggregateOutputType | null
  _min: TwitchUserMinAggregateOutputType | null
  _max: TwitchUserMaxAggregateOutputType | null
}

type GetTwitchUserGroupByPayload<T extends TwitchUserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TwitchUserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TwitchUserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TwitchUserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TwitchUserGroupByOutputType[P]>
      }
    >
  >



export type TwitchUserWhereInput = {
  AND?: Prisma.TwitchUserWhereInput | Prisma.TwitchUserWhereInput[]
  OR?: Prisma.TwitchUserWhereInput[]
  NOT?: Prisma.TwitchUserWhereInput | Prisma.TwitchUserWhereInput[]
  id?: Prisma.StringFilter<"TwitchUser"> | string
  accessToken?: Prisma.StringFilter<"TwitchUser"> | string
  refreshToken?: Prisma.StringFilter<"TwitchUser"> | string
  expiresAt?: Prisma.DateTimeFilter<"TwitchUser"> | Date | string
  scope?: Prisma.StringFilter<"TwitchUser"> | string
  isValid?: Prisma.BoolFilter<"TwitchUser"> | boolean
  login?: Prisma.StringFilter<"TwitchUser"> | string
  displayName?: Prisma.StringFilter<"TwitchUser"> | string
  profileImage?: Prisma.StringNullableFilter<"TwitchUser"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TwitchUser"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TwitchUser"> | Date | string
  Session?: Prisma.SessionListRelationFilter
}

export type TwitchUserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  isValid?: Prisma.SortOrder
  login?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  profileImage?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  Session?: Prisma.SessionOrderByRelationAggregateInput
}

export type TwitchUserWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TwitchUserWhereInput | Prisma.TwitchUserWhereInput[]
  OR?: Prisma.TwitchUserWhereInput[]
  NOT?: Prisma.TwitchUserWhereInput | Prisma.TwitchUserWhereInput[]
  accessToken?: Prisma.StringFilter<"TwitchUser"> | string
  refreshToken?: Prisma.StringFilter<"TwitchUser"> | string
  expiresAt?: Prisma.DateTimeFilter<"TwitchUser"> | Date | string
  scope?: Prisma.StringFilter<"TwitchUser"> | string
  isValid?: Prisma.BoolFilter<"TwitchUser"> | boolean
  login?: Prisma.StringFilter<"TwitchUser"> | string
  displayName?: Prisma.StringFilter<"TwitchUser"> | string
  profileImage?: Prisma.StringNullableFilter<"TwitchUser"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TwitchUser"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TwitchUser"> | Date | string
  Session?: Prisma.SessionListRelationFilter
}, "id">

export type TwitchUserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  isValid?: Prisma.SortOrder
  login?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  profileImage?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TwitchUserCountOrderByAggregateInput
  _max?: Prisma.TwitchUserMaxOrderByAggregateInput
  _min?: Prisma.TwitchUserMinOrderByAggregateInput
}

export type TwitchUserScalarWhereWithAggregatesInput = {
  AND?: Prisma.TwitchUserScalarWhereWithAggregatesInput | Prisma.TwitchUserScalarWhereWithAggregatesInput[]
  OR?: Prisma.TwitchUserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TwitchUserScalarWhereWithAggregatesInput | Prisma.TwitchUserScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TwitchUser"> | string
  accessToken?: Prisma.StringWithAggregatesFilter<"TwitchUser"> | string
  refreshToken?: Prisma.StringWithAggregatesFilter<"TwitchUser"> | string
  expiresAt?: Prisma.DateTimeWithAggregatesFilter<"TwitchUser"> | Date | string
  scope?: Prisma.StringWithAggregatesFilter<"TwitchUser"> | string
  isValid?: Prisma.BoolWithAggregatesFilter<"TwitchUser"> | boolean
  login?: Prisma.StringWithAggregatesFilter<"TwitchUser"> | string
  displayName?: Prisma.StringWithAggregatesFilter<"TwitchUser"> | string
  profileImage?: Prisma.StringNullableWithAggregatesFilter<"TwitchUser"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TwitchUser"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TwitchUser"> | Date | string
}

export type TwitchUserCreateInput = {
  id: string
  accessToken: string
  refreshToken: string
  expiresAt: Date | string
  scope: string
  isValid?: boolean
  login: string
  displayName: string
  profileImage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  Session?: Prisma.SessionCreateNestedManyWithoutUserInput
}

export type TwitchUserUncheckedCreateInput = {
  id: string
  accessToken: string
  refreshToken: string
  expiresAt: Date | string
  scope: string
  isValid?: boolean
  login: string
  displayName: string
  profileImage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  Session?: Prisma.SessionUncheckedCreateNestedManyWithoutUserInput
}

export type TwitchUserUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  isValid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  login?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Session?: Prisma.SessionUpdateManyWithoutUserNestedInput
}

export type TwitchUserUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  isValid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  login?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Session?: Prisma.SessionUncheckedUpdateManyWithoutUserNestedInput
}

export type TwitchUserCreateManyInput = {
  id: string
  accessToken: string
  refreshToken: string
  expiresAt: Date | string
  scope: string
  isValid?: boolean
  login: string
  displayName: string
  profileImage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TwitchUserUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  isValid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  login?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TwitchUserUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  isValid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  login?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TwitchUserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  isValid?: Prisma.SortOrder
  login?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  profileImage?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TwitchUserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  isValid?: Prisma.SortOrder
  login?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  profileImage?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TwitchUserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  isValid?: Prisma.SortOrder
  login?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  profileImage?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TwitchUserScalarRelationFilter = {
  is?: Prisma.TwitchUserWhereInput
  isNot?: Prisma.TwitchUserWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type TwitchUserCreateNestedOneWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.TwitchUserCreateWithoutSessionInput, Prisma.TwitchUserUncheckedCreateWithoutSessionInput>
  connectOrCreate?: Prisma.TwitchUserCreateOrConnectWithoutSessionInput
  connect?: Prisma.TwitchUserWhereUniqueInput
}

export type TwitchUserUpdateOneRequiredWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.TwitchUserCreateWithoutSessionInput, Prisma.TwitchUserUncheckedCreateWithoutSessionInput>
  connectOrCreate?: Prisma.TwitchUserCreateOrConnectWithoutSessionInput
  upsert?: Prisma.TwitchUserUpsertWithoutSessionInput
  connect?: Prisma.TwitchUserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TwitchUserUpdateToOneWithWhereWithoutSessionInput, Prisma.TwitchUserUpdateWithoutSessionInput>, Prisma.TwitchUserUncheckedUpdateWithoutSessionInput>
}

export type TwitchUserCreateWithoutSessionInput = {
  id: string
  accessToken: string
  refreshToken: string
  expiresAt: Date | string
  scope: string
  isValid?: boolean
  login: string
  displayName: string
  profileImage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TwitchUserUncheckedCreateWithoutSessionInput = {
  id: string
  accessToken: string
  refreshToken: string
  expiresAt: Date | string
  scope: string
  isValid?: boolean
  login: string
  displayName: string
  profileImage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TwitchUserCreateOrConnectWithoutSessionInput = {
  where: Prisma.TwitchUserWhereUniqueInput
  create: Prisma.XOR<Prisma.TwitchUserCreateWithoutSessionInput, Prisma.TwitchUserUncheckedCreateWithoutSessionInput>
}

export type TwitchUserUpsertWithoutSessionInput = {
  update: Prisma.XOR<Prisma.TwitchUserUpdateWithoutSessionInput, Prisma.TwitchUserUncheckedUpdateWithoutSessionInput>
  create: Prisma.XOR<Prisma.TwitchUserCreateWithoutSessionInput, Prisma.TwitchUserUncheckedCreateWithoutSessionInput>
  where?: Prisma.TwitchUserWhereInput
}

export type TwitchUserUpdateToOneWithWhereWithoutSessionInput = {
  where?: Prisma.TwitchUserWhereInput
  data: Prisma.XOR<Prisma.TwitchUserUpdateWithoutSessionInput, Prisma.TwitchUserUncheckedUpdateWithoutSessionInput>
}

export type TwitchUserUpdateWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  isValid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  login?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TwitchUserUncheckedUpdateWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  isValid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  login?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TwitchUserCountOutputType
 */

export type TwitchUserCountOutputType = {
  Session: number
}

export type TwitchUserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Session?: boolean | TwitchUserCountOutputTypeCountSessionArgs
}

/**
 * TwitchUserCountOutputType without action
 */
export type TwitchUserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwitchUserCountOutputType
   */
  select?: Prisma.TwitchUserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TwitchUserCountOutputType without action
 */
export type TwitchUserCountOutputTypeCountSessionArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionWhereInput
}


export type TwitchUserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accessToken?: boolean
  refreshToken?: boolean
  expiresAt?: boolean
  scope?: boolean
  isValid?: boolean
  login?: boolean
  displayName?: boolean
  profileImage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  Session?: boolean | Prisma.TwitchUser$SessionArgs<ExtArgs>
  _count?: boolean | Prisma.TwitchUserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["twitchUser"]>

export type TwitchUserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accessToken?: boolean
  refreshToken?: boolean
  expiresAt?: boolean
  scope?: boolean
  isValid?: boolean
  login?: boolean
  displayName?: boolean
  profileImage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["twitchUser"]>

export type TwitchUserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accessToken?: boolean
  refreshToken?: boolean
  expiresAt?: boolean
  scope?: boolean
  isValid?: boolean
  login?: boolean
  displayName?: boolean
  profileImage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["twitchUser"]>

export type TwitchUserSelectScalar = {
  id?: boolean
  accessToken?: boolean
  refreshToken?: boolean
  expiresAt?: boolean
  scope?: boolean
  isValid?: boolean
  login?: boolean
  displayName?: boolean
  profileImage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TwitchUserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "accessToken" | "refreshToken" | "expiresAt" | "scope" | "isValid" | "login" | "displayName" | "profileImage" | "createdAt" | "updatedAt", ExtArgs["result"]["twitchUser"]>
export type TwitchUserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Session?: boolean | Prisma.TwitchUser$SessionArgs<ExtArgs>
  _count?: boolean | Prisma.TwitchUserCountOutputTypeDefaultArgs<ExtArgs>
}
export type TwitchUserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type TwitchUserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $TwitchUserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TwitchUser"
  objects: {
    Session: Prisma.$SessionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    accessToken: string
    refreshToken: string
    expiresAt: Date
    scope: string
    isValid: boolean
    login: string
    displayName: string
    profileImage: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["twitchUser"]>
  composites: {}
}

export type TwitchUserGetPayload<S extends boolean | null | undefined | TwitchUserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TwitchUserPayload, S>

export type TwitchUserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TwitchUserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TwitchUserCountAggregateInputType | true
  }

export interface TwitchUserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TwitchUser'], meta: { name: 'TwitchUser' } }
  /**
   * Find zero or one TwitchUser that matches the filter.
   * @param {TwitchUserFindUniqueArgs} args - Arguments to find a TwitchUser
   * @example
   * // Get one TwitchUser
   * const twitchUser = await prisma.twitchUser.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TwitchUserFindUniqueArgs>(args: Prisma.SelectSubset<T, TwitchUserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TwitchUserClient<runtime.Types.Result.GetResult<Prisma.$TwitchUserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TwitchUser that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TwitchUserFindUniqueOrThrowArgs} args - Arguments to find a TwitchUser
   * @example
   * // Get one TwitchUser
   * const twitchUser = await prisma.twitchUser.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TwitchUserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TwitchUserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TwitchUserClient<runtime.Types.Result.GetResult<Prisma.$TwitchUserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TwitchUser that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TwitchUserFindFirstArgs} args - Arguments to find a TwitchUser
   * @example
   * // Get one TwitchUser
   * const twitchUser = await prisma.twitchUser.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TwitchUserFindFirstArgs>(args?: Prisma.SelectSubset<T, TwitchUserFindFirstArgs<ExtArgs>>): Prisma.Prisma__TwitchUserClient<runtime.Types.Result.GetResult<Prisma.$TwitchUserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TwitchUser that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TwitchUserFindFirstOrThrowArgs} args - Arguments to find a TwitchUser
   * @example
   * // Get one TwitchUser
   * const twitchUser = await prisma.twitchUser.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TwitchUserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TwitchUserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TwitchUserClient<runtime.Types.Result.GetResult<Prisma.$TwitchUserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TwitchUsers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TwitchUserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TwitchUsers
   * const twitchUsers = await prisma.twitchUser.findMany()
   * 
   * // Get first 10 TwitchUsers
   * const twitchUsers = await prisma.twitchUser.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const twitchUserWithIdOnly = await prisma.twitchUser.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TwitchUserFindManyArgs>(args?: Prisma.SelectSubset<T, TwitchUserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TwitchUserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TwitchUser.
   * @param {TwitchUserCreateArgs} args - Arguments to create a TwitchUser.
   * @example
   * // Create one TwitchUser
   * const TwitchUser = await prisma.twitchUser.create({
   *   data: {
   *     // ... data to create a TwitchUser
   *   }
   * })
   * 
   */
  create<T extends TwitchUserCreateArgs>(args: Prisma.SelectSubset<T, TwitchUserCreateArgs<ExtArgs>>): Prisma.Prisma__TwitchUserClient<runtime.Types.Result.GetResult<Prisma.$TwitchUserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TwitchUsers.
   * @param {TwitchUserCreateManyArgs} args - Arguments to create many TwitchUsers.
   * @example
   * // Create many TwitchUsers
   * const twitchUser = await prisma.twitchUser.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TwitchUserCreateManyArgs>(args?: Prisma.SelectSubset<T, TwitchUserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TwitchUsers and returns the data saved in the database.
   * @param {TwitchUserCreateManyAndReturnArgs} args - Arguments to create many TwitchUsers.
   * @example
   * // Create many TwitchUsers
   * const twitchUser = await prisma.twitchUser.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TwitchUsers and only return the `id`
   * const twitchUserWithIdOnly = await prisma.twitchUser.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TwitchUserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TwitchUserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TwitchUserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TwitchUser.
   * @param {TwitchUserDeleteArgs} args - Arguments to delete one TwitchUser.
   * @example
   * // Delete one TwitchUser
   * const TwitchUser = await prisma.twitchUser.delete({
   *   where: {
   *     // ... filter to delete one TwitchUser
   *   }
   * })
   * 
   */
  delete<T extends TwitchUserDeleteArgs>(args: Prisma.SelectSubset<T, TwitchUserDeleteArgs<ExtArgs>>): Prisma.Prisma__TwitchUserClient<runtime.Types.Result.GetResult<Prisma.$TwitchUserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TwitchUser.
   * @param {TwitchUserUpdateArgs} args - Arguments to update one TwitchUser.
   * @example
   * // Update one TwitchUser
   * const twitchUser = await prisma.twitchUser.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TwitchUserUpdateArgs>(args: Prisma.SelectSubset<T, TwitchUserUpdateArgs<ExtArgs>>): Prisma.Prisma__TwitchUserClient<runtime.Types.Result.GetResult<Prisma.$TwitchUserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TwitchUsers.
   * @param {TwitchUserDeleteManyArgs} args - Arguments to filter TwitchUsers to delete.
   * @example
   * // Delete a few TwitchUsers
   * const { count } = await prisma.twitchUser.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TwitchUserDeleteManyArgs>(args?: Prisma.SelectSubset<T, TwitchUserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TwitchUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TwitchUserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TwitchUsers
   * const twitchUser = await prisma.twitchUser.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TwitchUserUpdateManyArgs>(args: Prisma.SelectSubset<T, TwitchUserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TwitchUsers and returns the data updated in the database.
   * @param {TwitchUserUpdateManyAndReturnArgs} args - Arguments to update many TwitchUsers.
   * @example
   * // Update many TwitchUsers
   * const twitchUser = await prisma.twitchUser.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TwitchUsers and only return the `id`
   * const twitchUserWithIdOnly = await prisma.twitchUser.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TwitchUserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TwitchUserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TwitchUserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TwitchUser.
   * @param {TwitchUserUpsertArgs} args - Arguments to update or create a TwitchUser.
   * @example
   * // Update or create a TwitchUser
   * const twitchUser = await prisma.twitchUser.upsert({
   *   create: {
   *     // ... data to create a TwitchUser
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TwitchUser we want to update
   *   }
   * })
   */
  upsert<T extends TwitchUserUpsertArgs>(args: Prisma.SelectSubset<T, TwitchUserUpsertArgs<ExtArgs>>): Prisma.Prisma__TwitchUserClient<runtime.Types.Result.GetResult<Prisma.$TwitchUserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TwitchUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TwitchUserCountArgs} args - Arguments to filter TwitchUsers to count.
   * @example
   * // Count the number of TwitchUsers
   * const count = await prisma.twitchUser.count({
   *   where: {
   *     // ... the filter for the TwitchUsers we want to count
   *   }
   * })
  **/
  count<T extends TwitchUserCountArgs>(
    args?: Prisma.Subset<T, TwitchUserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TwitchUserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TwitchUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TwitchUserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TwitchUserAggregateArgs>(args: Prisma.Subset<T, TwitchUserAggregateArgs>): Prisma.PrismaPromise<GetTwitchUserAggregateType<T>>

  /**
   * Group by TwitchUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TwitchUserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TwitchUserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TwitchUserGroupByArgs['orderBy'] }
      : { orderBy?: TwitchUserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TwitchUserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTwitchUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TwitchUser model
 */
readonly fields: TwitchUserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TwitchUser.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TwitchUserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Session<T extends Prisma.TwitchUser$SessionArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TwitchUser$SessionArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TwitchUser model
 */
export interface TwitchUserFieldRefs {
  readonly id: Prisma.FieldRef<"TwitchUser", 'String'>
  readonly accessToken: Prisma.FieldRef<"TwitchUser", 'String'>
  readonly refreshToken: Prisma.FieldRef<"TwitchUser", 'String'>
  readonly expiresAt: Prisma.FieldRef<"TwitchUser", 'DateTime'>
  readonly scope: Prisma.FieldRef<"TwitchUser", 'String'>
  readonly isValid: Prisma.FieldRef<"TwitchUser", 'Boolean'>
  readonly login: Prisma.FieldRef<"TwitchUser", 'String'>
  readonly displayName: Prisma.FieldRef<"TwitchUser", 'String'>
  readonly profileImage: Prisma.FieldRef<"TwitchUser", 'String'>
  readonly createdAt: Prisma.FieldRef<"TwitchUser", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TwitchUser", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TwitchUser findUnique
 */
export type TwitchUserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwitchUser
   */
  select?: Prisma.TwitchUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwitchUser
   */
  omit?: Prisma.TwitchUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwitchUserInclude<ExtArgs> | null
  /**
   * Filter, which TwitchUser to fetch.
   */
  where: Prisma.TwitchUserWhereUniqueInput
}

/**
 * TwitchUser findUniqueOrThrow
 */
export type TwitchUserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwitchUser
   */
  select?: Prisma.TwitchUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwitchUser
   */
  omit?: Prisma.TwitchUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwitchUserInclude<ExtArgs> | null
  /**
   * Filter, which TwitchUser to fetch.
   */
  where: Prisma.TwitchUserWhereUniqueInput
}

/**
 * TwitchUser findFirst
 */
export type TwitchUserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwitchUser
   */
  select?: Prisma.TwitchUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwitchUser
   */
  omit?: Prisma.TwitchUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwitchUserInclude<ExtArgs> | null
  /**
   * Filter, which TwitchUser to fetch.
   */
  where?: Prisma.TwitchUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TwitchUsers to fetch.
   */
  orderBy?: Prisma.TwitchUserOrderByWithRelationInput | Prisma.TwitchUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TwitchUsers.
   */
  cursor?: Prisma.TwitchUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TwitchUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TwitchUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TwitchUsers.
   */
  distinct?: Prisma.TwitchUserScalarFieldEnum | Prisma.TwitchUserScalarFieldEnum[]
}

/**
 * TwitchUser findFirstOrThrow
 */
export type TwitchUserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwitchUser
   */
  select?: Prisma.TwitchUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwitchUser
   */
  omit?: Prisma.TwitchUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwitchUserInclude<ExtArgs> | null
  /**
   * Filter, which TwitchUser to fetch.
   */
  where?: Prisma.TwitchUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TwitchUsers to fetch.
   */
  orderBy?: Prisma.TwitchUserOrderByWithRelationInput | Prisma.TwitchUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TwitchUsers.
   */
  cursor?: Prisma.TwitchUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TwitchUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TwitchUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TwitchUsers.
   */
  distinct?: Prisma.TwitchUserScalarFieldEnum | Prisma.TwitchUserScalarFieldEnum[]
}

/**
 * TwitchUser findMany
 */
export type TwitchUserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwitchUser
   */
  select?: Prisma.TwitchUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwitchUser
   */
  omit?: Prisma.TwitchUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwitchUserInclude<ExtArgs> | null
  /**
   * Filter, which TwitchUsers to fetch.
   */
  where?: Prisma.TwitchUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TwitchUsers to fetch.
   */
  orderBy?: Prisma.TwitchUserOrderByWithRelationInput | Prisma.TwitchUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TwitchUsers.
   */
  cursor?: Prisma.TwitchUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TwitchUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TwitchUsers.
   */
  skip?: number
  distinct?: Prisma.TwitchUserScalarFieldEnum | Prisma.TwitchUserScalarFieldEnum[]
}

/**
 * TwitchUser create
 */
export type TwitchUserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwitchUser
   */
  select?: Prisma.TwitchUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwitchUser
   */
  omit?: Prisma.TwitchUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwitchUserInclude<ExtArgs> | null
  /**
   * The data needed to create a TwitchUser.
   */
  data: Prisma.XOR<Prisma.TwitchUserCreateInput, Prisma.TwitchUserUncheckedCreateInput>
}

/**
 * TwitchUser createMany
 */
export type TwitchUserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TwitchUsers.
   */
  data: Prisma.TwitchUserCreateManyInput | Prisma.TwitchUserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TwitchUser createManyAndReturn
 */
export type TwitchUserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwitchUser
   */
  select?: Prisma.TwitchUserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TwitchUser
   */
  omit?: Prisma.TwitchUserOmit<ExtArgs> | null
  /**
   * The data used to create many TwitchUsers.
   */
  data: Prisma.TwitchUserCreateManyInput | Prisma.TwitchUserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TwitchUser update
 */
export type TwitchUserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwitchUser
   */
  select?: Prisma.TwitchUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwitchUser
   */
  omit?: Prisma.TwitchUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwitchUserInclude<ExtArgs> | null
  /**
   * The data needed to update a TwitchUser.
   */
  data: Prisma.XOR<Prisma.TwitchUserUpdateInput, Prisma.TwitchUserUncheckedUpdateInput>
  /**
   * Choose, which TwitchUser to update.
   */
  where: Prisma.TwitchUserWhereUniqueInput
}

/**
 * TwitchUser updateMany
 */
export type TwitchUserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TwitchUsers.
   */
  data: Prisma.XOR<Prisma.TwitchUserUpdateManyMutationInput, Prisma.TwitchUserUncheckedUpdateManyInput>
  /**
   * Filter which TwitchUsers to update
   */
  where?: Prisma.TwitchUserWhereInput
  /**
   * Limit how many TwitchUsers to update.
   */
  limit?: number
}

/**
 * TwitchUser updateManyAndReturn
 */
export type TwitchUserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwitchUser
   */
  select?: Prisma.TwitchUserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TwitchUser
   */
  omit?: Prisma.TwitchUserOmit<ExtArgs> | null
  /**
   * The data used to update TwitchUsers.
   */
  data: Prisma.XOR<Prisma.TwitchUserUpdateManyMutationInput, Prisma.TwitchUserUncheckedUpdateManyInput>
  /**
   * Filter which TwitchUsers to update
   */
  where?: Prisma.TwitchUserWhereInput
  /**
   * Limit how many TwitchUsers to update.
   */
  limit?: number
}

/**
 * TwitchUser upsert
 */
export type TwitchUserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwitchUser
   */
  select?: Prisma.TwitchUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwitchUser
   */
  omit?: Prisma.TwitchUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwitchUserInclude<ExtArgs> | null
  /**
   * The filter to search for the TwitchUser to update in case it exists.
   */
  where: Prisma.TwitchUserWhereUniqueInput
  /**
   * In case the TwitchUser found by the `where` argument doesn't exist, create a new TwitchUser with this data.
   */
  create: Prisma.XOR<Prisma.TwitchUserCreateInput, Prisma.TwitchUserUncheckedCreateInput>
  /**
   * In case the TwitchUser was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TwitchUserUpdateInput, Prisma.TwitchUserUncheckedUpdateInput>
}

/**
 * TwitchUser delete
 */
export type TwitchUserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwitchUser
   */
  select?: Prisma.TwitchUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwitchUser
   */
  omit?: Prisma.TwitchUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwitchUserInclude<ExtArgs> | null
  /**
   * Filter which TwitchUser to delete.
   */
  where: Prisma.TwitchUserWhereUniqueInput
}

/**
 * TwitchUser deleteMany
 */
export type TwitchUserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TwitchUsers to delete
   */
  where?: Prisma.TwitchUserWhereInput
  /**
   * Limit how many TwitchUsers to delete.
   */
  limit?: number
}

/**
 * TwitchUser.Session
 */
export type TwitchUser$SessionArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  where?: Prisma.SessionWhereInput
  orderBy?: Prisma.SessionOrderByWithRelationInput | Prisma.SessionOrderByWithRelationInput[]
  cursor?: Prisma.SessionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SessionScalarFieldEnum | Prisma.SessionScalarFieldEnum[]
}

/**
 * TwitchUser without action
 */
export type TwitchUserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TwitchUser
   */
  select?: Prisma.TwitchUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TwitchUser
   */
  omit?: Prisma.TwitchUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TwitchUserInclude<ExtArgs> | null
}
